/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVideoaulasRouteImport } from './routes/_authenticated/videoaulas'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedRevisarRouteImport } from './routes/_authenticated/revisar'
import { Route as AuthenticatedResumosRouteImport } from './routes/_authenticated/resumos'
import { Route as AuthenticatedRedacaoRouteImport } from './routes/_authenticated/redacao'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedFocoRouteImport } from './routes/_authenticated/foco'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as AuthenticatedTutorIndexRouteImport } from './routes/_authenticated/tutor.index'
import { Route as AuthenticatedSimuladosIndexRouteImport } from './routes/_authenticated/simulados.index'
import { Route as AuthenticatedTutorThreadIdRouteImport } from './routes/_authenticated/tutor.$threadId'
import { Route as AuthenticatedResumosDocumentIdRouteImport } from './routes/_authenticated/resumos.$documentId'
import { Route as AuthenticatedFlashcardsDeckIdRouteImport } from './routes/_authenticated/flashcards.$deckId'
import { Route as AuthenticatedSimuladosAttemptIdIndexRouteImport } from './routes/_authenticated/simulados.$attemptId.index'
import { Route as ApiPublicHooksGenerateDailyPlansRouteImport } from './routes/api/public/hooks/generate-daily-plans'
import { Route as AuthenticatedSimuladosAttemptIdResultadoRouteImport } from './routes/_authenticated/simulados.$attemptId.resultado'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoaulasRoute = AuthenticatedVideoaulasRouteImport.update({
  id: '/videoaulas',
  path: '/videoaulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisarRoute = AuthenticatedRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumosRoute = AuthenticatedResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedacaoRoute = AuthenticatedRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFocoRoute = AuthenticatedFocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorIndexRoute = AuthenticatedTutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedSimuladosIndexRoute =
  AuthenticatedSimuladosIndexRouteImport.update({
    id: '/simulados/',
    path: '/simulados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTutorThreadIdRoute =
  AuthenticatedTutorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedResumosDocumentIdRoute =
  AuthenticatedResumosDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedResumosRoute,
  } as any)
const AuthenticatedFlashcardsDeckIdRoute =
  AuthenticatedFlashcardsDeckIdRouteImport.update({
    id: '/$deckId',
    path: '/$deckId',
    getParentRoute: () => AuthenticatedFlashcardsRoute,
  } as any)
const AuthenticatedSimuladosAttemptIdIndexRoute =
  AuthenticatedSimuladosAttemptIdIndexRouteImport.update({
    id: '/simulados/$attemptId/',
    path: '/simulados/$attemptId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksGenerateDailyPlansRoute =
  ApiPublicHooksGenerateDailyPlansRouteImport.update({
    id: '/api/public/hooks/generate-daily-plans',
    path: '/api/public/hooks/generate-daily-plans',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSimuladosAttemptIdResultadoRoute =
  AuthenticatedSimuladosAttemptIdResultadoRouteImport.update({
    id: '/simulados/$attemptId/resultado',
    path: '/simulados/$attemptId/resultado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRouteWithChildren
  '/foco': typeof AuthenticatedFocoRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/resumos': typeof AuthenticatedResumosRouteWithChildren
  '/revisar': typeof AuthenticatedRevisarRoute
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/resumos/$documentId': typeof AuthenticatedResumosDocumentIdRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/simulados/': typeof AuthenticatedSimuladosIndexRoute
  '/tutor/': typeof AuthenticatedTutorIndexRoute
  '/simulados/$attemptId/resultado': typeof AuthenticatedSimuladosAttemptIdResultadoRoute
  '/api/public/hooks/generate-daily-plans': typeof ApiPublicHooksGenerateDailyPlansRoute
  '/simulados/$attemptId/': typeof AuthenticatedSimuladosAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRouteWithChildren
  '/foco': typeof AuthenticatedFocoRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/resumos': typeof AuthenticatedResumosRouteWithChildren
  '/revisar': typeof AuthenticatedRevisarRoute
  '/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/resumos/$documentId': typeof AuthenticatedResumosDocumentIdRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/simulados': typeof AuthenticatedSimuladosIndexRoute
  '/tutor': typeof AuthenticatedTutorIndexRoute
  '/simulados/$attemptId/resultado': typeof AuthenticatedSimuladosAttemptIdResultadoRoute
  '/api/public/hooks/generate-daily-plans': typeof ApiPublicHooksGenerateDailyPlansRoute
  '/simulados/$attemptId': typeof AuthenticatedSimuladosAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRouteWithChildren
  '/_authenticated/foco': typeof AuthenticatedFocoRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/redacao': typeof AuthenticatedRedacaoRoute
  '/_authenticated/resumos': typeof AuthenticatedResumosRouteWithChildren
  '/_authenticated/revisar': typeof AuthenticatedRevisarRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/_authenticated/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/_authenticated/resumos/$documentId': typeof AuthenticatedResumosDocumentIdRoute
  '/_authenticated/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/_authenticated/simulados/': typeof AuthenticatedSimuladosIndexRoute
  '/_authenticated/tutor/': typeof AuthenticatedTutorIndexRoute
  '/_authenticated/simulados/$attemptId/resultado': typeof AuthenticatedSimuladosAttemptIdResultadoRoute
  '/api/public/hooks/generate-daily-plans': typeof ApiPublicHooksGenerateDailyPlansRoute
  '/_authenticated/simulados/$attemptId/': typeof AuthenticatedSimuladosAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/amigos'
    | '/calendario'
    | '/conquistas'
    | '/dashboard'
    | '/flashcards'
    | '/foco'
    | '/loja'
    | '/metas'
    | '/onboarding'
    | '/ranking'
    | '/redacao'
    | '/resumos'
    | '/revisar'
    | '/tutor'
    | '/videoaulas'
    | '/api/chat'
    | '/flashcards/$deckId'
    | '/resumos/$documentId'
    | '/tutor/$threadId'
    | '/simulados/'
    | '/tutor/'
    | '/simulados/$attemptId/resultado'
    | '/api/public/hooks/generate-daily-plans'
    | '/simulados/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/amigos'
    | '/calendario'
    | '/conquistas'
    | '/dashboard'
    | '/flashcards'
    | '/foco'
    | '/loja'
    | '/metas'
    | '/onboarding'
    | '/ranking'
    | '/redacao'
    | '/resumos'
    | '/revisar'
    | '/videoaulas'
    | '/api/chat'
    | '/flashcards/$deckId'
    | '/resumos/$documentId'
    | '/tutor/$threadId'
    | '/simulados'
    | '/tutor'
    | '/simulados/$attemptId/resultado'
    | '/api/public/hooks/generate-daily-plans'
    | '/simulados/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/amigos'
    | '/_authenticated/calendario'
    | '/_authenticated/conquistas'
    | '/_authenticated/dashboard'
    | '/_authenticated/flashcards'
    | '/_authenticated/foco'
    | '/_authenticated/loja'
    | '/_authenticated/metas'
    | '/_authenticated/onboarding'
    | '/_authenticated/ranking'
    | '/_authenticated/redacao'
    | '/_authenticated/resumos'
    | '/_authenticated/revisar'
    | '/_authenticated/tutor'
    | '/_authenticated/videoaulas'
    | '/api/chat'
    | '/_authenticated/flashcards/$deckId'
    | '/_authenticated/resumos/$documentId'
    | '/_authenticated/tutor/$threadId'
    | '/_authenticated/simulados/'
    | '/_authenticated/tutor/'
    | '/_authenticated/simulados/$attemptId/resultado'
    | '/api/public/hooks/generate-daily-plans'
    | '/_authenticated/simulados/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksGenerateDailyPlansRoute: typeof ApiPublicHooksGenerateDailyPlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videoaulas': {
      id: '/_authenticated/videoaulas'
      path: '/videoaulas'
      fullPath: '/videoaulas'
      preLoaderRoute: typeof AuthenticatedVideoaulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar': {
      id: '/_authenticated/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof AuthenticatedRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumos': {
      id: '/_authenticated/resumos'
      path: '/resumos'
      fullPath: '/resumos'
      preLoaderRoute: typeof AuthenticatedResumosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redacao': {
      id: '/_authenticated/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof AuthenticatedRedacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foco': {
      id: '/_authenticated/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof AuthenticatedFocoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/': {
      id: '/_authenticated/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AuthenticatedTutorIndexRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/simulados/': {
      id: '/_authenticated/simulados/'
      path: '/simulados'
      fullPath: '/simulados/'
      preLoaderRoute: typeof AuthenticatedSimuladosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/$threadId': {
      id: '/_authenticated/tutor/$threadId'
      path: '/$threadId'
      fullPath: '/tutor/$threadId'
      preLoaderRoute: typeof AuthenticatedTutorThreadIdRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/resumos/$documentId': {
      id: '/_authenticated/resumos/$documentId'
      path: '/$documentId'
      fullPath: '/resumos/$documentId'
      preLoaderRoute: typeof AuthenticatedResumosDocumentIdRouteImport
      parentRoute: typeof AuthenticatedResumosRoute
    }
    '/_authenticated/flashcards/$deckId': {
      id: '/_authenticated/flashcards/$deckId'
      path: '/$deckId'
      fullPath: '/flashcards/$deckId'
      preLoaderRoute: typeof AuthenticatedFlashcardsDeckIdRouteImport
      parentRoute: typeof AuthenticatedFlashcardsRoute
    }
    '/_authenticated/simulados/$attemptId/': {
      id: '/_authenticated/simulados/$attemptId/'
      path: '/simulados/$attemptId'
      fullPath: '/simulados/$attemptId/'
      preLoaderRoute: typeof AuthenticatedSimuladosAttemptIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-daily-plans': {
      id: '/api/public/hooks/generate-daily-plans'
      path: '/api/public/hooks/generate-daily-plans'
      fullPath: '/api/public/hooks/generate-daily-plans'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulados/$attemptId/resultado': {
      id: '/_authenticated/simulados/$attemptId/resultado'
      path: '/simulados/$attemptId/resultado'
      fullPath: '/simulados/$attemptId/resultado'
      preLoaderRoute: typeof AuthenticatedSimuladosAttemptIdResultadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFlashcardsRouteChildren {
  AuthenticatedFlashcardsDeckIdRoute: typeof AuthenticatedFlashcardsDeckIdRoute
}

const AuthenticatedFlashcardsRouteChildren: AuthenticatedFlashcardsRouteChildren =
  {
    AuthenticatedFlashcardsDeckIdRoute: AuthenticatedFlashcardsDeckIdRoute,
  }

const AuthenticatedFlashcardsRouteWithChildren =
  AuthenticatedFlashcardsRoute._addFileChildren(
    AuthenticatedFlashcardsRouteChildren,
  )

interface AuthenticatedResumosRouteChildren {
  AuthenticatedResumosDocumentIdRoute: typeof AuthenticatedResumosDocumentIdRoute
}

const AuthenticatedResumosRouteChildren: AuthenticatedResumosRouteChildren = {
  AuthenticatedResumosDocumentIdRoute: AuthenticatedResumosDocumentIdRoute,
}

const AuthenticatedResumosRouteWithChildren =
  AuthenticatedResumosRoute._addFileChildren(AuthenticatedResumosRouteChildren)

interface AuthenticatedTutorRouteChildren {
  AuthenticatedTutorThreadIdRoute: typeof AuthenticatedTutorThreadIdRoute
  AuthenticatedTutorIndexRoute: typeof AuthenticatedTutorIndexRoute
}

const AuthenticatedTutorRouteChildren: AuthenticatedTutorRouteChildren = {
  AuthenticatedTutorThreadIdRoute: AuthenticatedTutorThreadIdRoute,
  AuthenticatedTutorIndexRoute: AuthenticatedTutorIndexRoute,
}

const AuthenticatedTutorRouteWithChildren =
  AuthenticatedTutorRoute._addFileChildren(AuthenticatedTutorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRouteWithChildren
  AuthenticatedFocoRoute: typeof AuthenticatedFocoRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRedacaoRoute: typeof AuthenticatedRedacaoRoute
  AuthenticatedResumosRoute: typeof AuthenticatedResumosRouteWithChildren
  AuthenticatedRevisarRoute: typeof AuthenticatedRevisarRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRouteWithChildren
  AuthenticatedVideoaulasRoute: typeof AuthenticatedVideoaulasRoute
  AuthenticatedSimuladosIndexRoute: typeof AuthenticatedSimuladosIndexRoute
  AuthenticatedSimuladosAttemptIdResultadoRoute: typeof AuthenticatedSimuladosAttemptIdResultadoRoute
  AuthenticatedSimuladosAttemptIdIndexRoute: typeof AuthenticatedSimuladosAttemptIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRouteWithChildren,
  AuthenticatedFocoRoute: AuthenticatedFocoRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRedacaoRoute: AuthenticatedRedacaoRoute,
  AuthenticatedResumosRoute: AuthenticatedResumosRouteWithChildren,
  AuthenticatedRevisarRoute: AuthenticatedRevisarRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRouteWithChildren,
  AuthenticatedVideoaulasRoute: AuthenticatedVideoaulasRoute,
  AuthenticatedSimuladosIndexRoute: AuthenticatedSimuladosIndexRoute,
  AuthenticatedSimuladosAttemptIdResultadoRoute:
    AuthenticatedSimuladosAttemptIdResultadoRoute,
  AuthenticatedSimuladosAttemptIdIndexRoute:
    AuthenticatedSimuladosAttemptIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksGenerateDailyPlansRoute: ApiPublicHooksGenerateDailyPlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
