/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVideoaulasRouteImport } from './routes/_authenticated/videoaulas'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedTutorIndexRouteImport } from './routes/_authenticated/tutor.index'
import { Route as AuthenticatedTutorThreadIdRouteImport } from './routes/_authenticated/tutor.$threadId'
import { Route as ApiPublicHooksGenerateDailyPlansRouteImport } from './routes/api/public/hooks/generate-daily-plans'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoaulasRoute = AuthenticatedVideoaulasRouteImport.update({
  id: '/videoaulas',
  path: '/videoaulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorIndexRoute = AuthenticatedTutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedTutorThreadIdRoute =
  AuthenticatedTutorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const ApiPublicHooksGenerateDailyPlansRoute =
  ApiPublicHooksGenerateDailyPlansRouteImport.update({
    id: '/api/public/hooks/generate-daily-plans',
    path: '/api/public/hooks/generate-daily-plans',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/tutor/': typeof AuthenticatedTutorIndexRoute
  '/api/public/hooks/generate-daily-plans': typeof ApiPublicHooksGenerateDailyPlansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/tutor': typeof AuthenticatedTutorIndexRoute
  '/api/public/hooks/generate-daily-plans': typeof ApiPublicHooksGenerateDailyPlansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/_authenticated/videoaulas': typeof AuthenticatedVideoaulasRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/tutor/$threadId': typeof AuthenticatedTutorThreadIdRoute
  '/_authenticated/tutor/': typeof AuthenticatedTutorIndexRoute
  '/api/public/hooks/generate-daily-plans': typeof ApiPublicHooksGenerateDailyPlansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/conquistas'
    | '/dashboard'
    | '/onboarding'
    | '/ranking'
    | '/tutor'
    | '/videoaulas'
    | '/api/chat'
    | '/tutor/$threadId'
    | '/tutor/'
    | '/api/public/hooks/generate-daily-plans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/conquistas'
    | '/dashboard'
    | '/onboarding'
    | '/ranking'
    | '/videoaulas'
    | '/api/chat'
    | '/tutor/$threadId'
    | '/tutor'
    | '/api/public/hooks/generate-daily-plans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendario'
    | '/_authenticated/conquistas'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/ranking'
    | '/_authenticated/tutor'
    | '/_authenticated/videoaulas'
    | '/api/chat'
    | '/_authenticated/tutor/$threadId'
    | '/_authenticated/tutor/'
    | '/api/public/hooks/generate-daily-plans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksGenerateDailyPlansRoute: typeof ApiPublicHooksGenerateDailyPlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videoaulas': {
      id: '/_authenticated/videoaulas'
      path: '/videoaulas'
      fullPath: '/videoaulas'
      preLoaderRoute: typeof AuthenticatedVideoaulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/': {
      id: '/_authenticated/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AuthenticatedTutorIndexRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/$threadId': {
      id: '/_authenticated/tutor/$threadId'
      path: '/$threadId'
      fullPath: '/tutor/$threadId'
      preLoaderRoute: typeof AuthenticatedTutorThreadIdRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/api/public/hooks/generate-daily-plans': {
      id: '/api/public/hooks/generate-daily-plans'
      path: '/api/public/hooks/generate-daily-plans'
      fullPath: '/api/public/hooks/generate-daily-plans'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTutorRouteChildren {
  AuthenticatedTutorThreadIdRoute: typeof AuthenticatedTutorThreadIdRoute
  AuthenticatedTutorIndexRoute: typeof AuthenticatedTutorIndexRoute
}

const AuthenticatedTutorRouteChildren: AuthenticatedTutorRouteChildren = {
  AuthenticatedTutorThreadIdRoute: AuthenticatedTutorThreadIdRoute,
  AuthenticatedTutorIndexRoute: AuthenticatedTutorIndexRoute,
}

const AuthenticatedTutorRouteWithChildren =
  AuthenticatedTutorRoute._addFileChildren(AuthenticatedTutorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRouteWithChildren
  AuthenticatedVideoaulasRoute: typeof AuthenticatedVideoaulasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRouteWithChildren,
  AuthenticatedVideoaulasRoute: AuthenticatedVideoaulasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksGenerateDailyPlansRoute: ApiPublicHooksGenerateDailyPlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
